### ISSUE TITLE
About Page

### ISSUE THREAD

**Issue by nbaker24** [cseitz/SoftwareEngineering-Team-TGMGPA#107]
An extra webpage that allows the user to see all our features and a little info about the app.

**Comment by cseitz** [comment]
President/Marketing should write up the contents of the about page.

@NolSpencer @nbaker24 @sli55

**Comment by nbaker24** [comment]
there is a doc in the google drive titled about page contents. that is where we are keeping all of our ideas that we come up with for the about page. we also will need to schedule a mini meeting for this to talk about any graphics that we do for this page.

**Comment by nbaker24** [comment]
![taskbook about page v1dark](https://user-images.githubusercontent.com/78121948/112400795-7b59a400-8cdf-11eb-9e02-54743ba6c047.png)
![taskbook about page v1light](https://user-images.githubusercontent.com/78121948/112400801-7eed2b00-8cdf-11eb-9507-959db9a4eaed.png)

these are the light and dark about page images

**Comment by sli55** [comment]
Hi Chris,

Sorry for didn't attending our meeting, I had trouble connecting to our
school vpn because currently I'm not in the states and the internet in my
quarantine hotel is so low and unstable. I have received your email and
once when you have scheduled a time for that meeting, send an email to
***@***.*** and I will join.

Best Regards,

Song
