### ISSUE TITLE
Task Deletion

### ISSUE THREAD

**Issue by cseitz** [cseitz/SoftwareEngineering-Team-TGMGPA#109]

**Comment by Chulz25** [comment]
for task deletion this is gonna require a iteration because the task ids are not aligned correctly with the 4 pre existing tasks they go in a different order than expected. 
For example in the today column the ids for the basic 2 tasks go from 3 then the one under it is 1
and for the tomorrow column the id= 4 then under it the id=2. 
Finishing code today before class today.

**Comment by Chulz25** [comment]
almost done with code but the inspect elements are different from firefox compared to chrome

Chrome delete xpath (//*[@id="task-6"]/div[1]/span/i[2] )
FireFox delete xpath (/html/body/div[2]/div[2]/span/span[2]/div/div[1]/span/i[2])

the code still works but breaks once task deletes
pushed code to test branch
