### ISSUE TITLE
Lessons Learned

### ISSUE THREAD

**Issue by cseitz** [cseitz/SoftwareEngineering-Team-TGMGPA#129]
Individual team members' lessons learned from this project.

**Comment by justintclark** [comment]
With this project, I learned a lot about what it means to work as a team to solve problems on a large scale project for a customer. Learning to utilize the SCUM/Agile practices made a big difference in the way actions gone done every week, and made it clearer how things could be organized for this kind of project. It gave a good glimpse of what to expect in the real world when it comes time to getting a job that uses this agile methodology. 

Of course, we had no shortages of challenges, when it came to personal lives, work lives, and medical/health issues. However, what's good about this is that agile development allows for breathing room with these kinds of events.

**Comment by jkeegan1** [comment]
Working with this team I learned what it meant to work in a larger size group and how everyone's role played an important part in its own way. I also learned a lot about backlogs and how level of importance of an issue plays a huge part in deciding whether or not an issue was sent to to that backlog for a later sprint.

**Comment by NolSpencer** [comment]
I learned a lot from this project. This project was the first introduction to any programming for a web app. It was also my first exposure to working as a group on a coding project. The things I learned for this process like Github, scrum, agile and the organization of sprints and of a repository all helped tremendously in the creation of this project. I learned how to work through problems with a team and set importance on what problems to tackle next.

**Comment by rsilvey1** [comment]
This semester, I learned more about how to work as a team in the software development process. I learned in detail the different parts of the scrum process and what each of the roles do. I also got experience with Python and web development in general.

**Comment by cseitz** [comment]
In this project, I gained insight and experience into leading a team of developers. In the past, I had frequently taken lead roles on projects but since my previous work was mostly freelance, there wasn't a considerable team aspect. While this project did not challenge me technically, I was significantly more challenged in people management, documentation, consistency, and leadership.

This project surely will be influential as preparation for my upcoming summer internship at Hyland Software where I will be a Cloud Infrastructure Administrator.

**Comment by JReese1212** [comment]
With this project, it gave me insight of working with a bigger team on a big project, and how everyones role plays a big part in the finish project. I learn more about the development process, and working with Selenium in python to test different components on the project.

**Comment by Chulz25** [comment]
During the development of this project, I have learned not only to be a test engineer but to finally collaborate on a project with multiple people with different roles. I have recently learned how to use selenium which made it a great fit in as me being a test engineer. I loved the different parts of scrum with this project, what also was interesting was the standups we would have every other day. These standups would show which of the members of the team were progressing or the ones that didn't make any progress at all. For this project, I feel like if we were all on campus it would be so cool to meet together for an actual standup meeting like software companies do but covid has taken those things away. I learned how to complete tasks during each sprint and be able to explain my ideology on why I did the test software a certain way.

This project helped me so much to be very influential for my test engineer position internship this summer which I am very grateful for.

**Comment by wesley-ka** [comment]
In my experience, the biggest challenge I faced was working alongside a team - and don't get me wrong, I was thrilled at the start of the semester to work on a project with my colleagues and really enjoyed the experience altogether. The main issue, which is something that I have been actively working on for the past few years, is the fact that I am not a very outgoing person, and sometimes I struggle to interact with others. I have full knowledge that this is something that I must improve, as working with others, alongside being much more efficient to achieve your and the team's shared goals, is personally very fulfilling. This project has presented itself as a very good opportunity for me to interact with other like-minded people to achieve a shared goal, and I feel that it gave me a very good insight into how working on a full-scale project in our area feels like, what are and how to solve the common issues that occur here and there, and how rewarding is to see the product of your team's efforts, after all the work that was done.

Also, thanks for everything everyone, I had a great time working with you all on this project.

**Comment by damaniwade** [comment]
This was the biggest team I've ever worked with for a group project. This was a very high-quality experience. Learning about Agile and the structure of scrum, how useful GitHub can be, and how multiple people working on little bits of a project can make it feel like progress is being made at a fast pace. 

My biggest challenge was feeling like I was useful to the team. I was the team's operations engineer, so I didn't feel I contributed as much until the end of the process. This was wrong of course because at the beginning I helped the team brainstorm what exactly we wanted to do with the software. So this project gave me a headstart on shifting my mindset from small school group projects to big team projects that I'll be experiencing when I go into the working world. Another challenge was working as an operations engineer. I've never experienced working in a server, putting an application on a server, and then making it run with GitHub actions. Very new, very interesting stuff. I understand now how useful all these skills are.

It was fun, I'll miss the team. They all work together great.

**Comment by cpfeifer** [comment]
During this project I faced quite a bit of struggles, I had some family issues to deal with that took me away from work, but also it had been a while since I had worked with the material we were coding so I basically needed to relearn all of it, along with new things being introduced to learn. I had also faced a bit of hesitance when it came to speaking up in such a big group. 

However, I learned a lot from this project, how to use my resources affectively, what it's like to work in such a big team that all have so many different talents, the process of software development and how everyone's role plays in it and the importance of communication. I really enjoyed this team and the project, hopefully I get to work with some of them again!

**Comment by nbaker24** [comment]
Throughout this project I think what challenged me the most was making sure that I was being as helpful to my team as I could be with the role that I had. This drove me to begin learning web deployment so I could just send people the website and have them give me feedback. This newly added skill is also what allowed me to secure an internship over the summer of redesigning a website.

**Comment by sli55** [comment]
Throughout the semester working with my teammates on this project, I really learned how important and how powerful if a group of people can collaborate in an effective way. During this pandemic, everything seems to be hugely affected and I believe if we can meet in person, working with my teammate would be a more interesting experience.

What I learned the most in the process of doing this project is the importance of characterizing people in a team into different roles and and how communicating effectively with each other helps the progress of the project. To some extend, this might be my first team working experience, I really enjoy working with my team.
