### ISSUE TITLE
Summary for Sprint 2/10 - 2/17

### ISSUE THREAD

**Issue by NolSpencer** [cseitz/SoftwareEngineering-Team-TGMGPA#24]
The following was accomplished in this sprint:
1. Coloring Tasks is Pending Review before being marked Completed
2. Progress on Vision Statement
3. Progress on Business Plan

During this sprint, we did not get as much done as we would have liked.

Due to it being our first sprint, we all had unfamiliarities and uncertainties with the process itself and we were not able to get much done, but we have identified new ways to restructure and organize to be significantly better prepared for the next sprint.

The following changes have been made in an effort to resolve these problems for future sprints:
1. A shared calendar has been created with meeting times and check-in times
2. Mandatory check-in by 7 PM on Saturdays and Sundays has been established. Team Members must report what they are doing or why they are not doing anything by 7 PM on those days. This ensures we know who's doing what, that they are actually doing it, and if not; how can we adapt to work not getting done.
3. Monday meetings have been moved to before class to better prepare for the presentation of each sprint to Dr. Delozier.
4. An additional meeting on Friday from 2 to 3 PM has been scheduled for each week.
5. A shift will be made to focus on one or two team-voted feature requests per sprint, rather than being the full scope of the spirit. Many more minor features, adjustments, and bug fixes will be focused on per sprint instead.
6. In-Depth meeting notes have become official. All important meeting topics are now transcripted by the group Marketing Analyst and President.

Hopefully, these changes will make next week's sprint more programming related.

**Comment by cseitz** [comment]
Summary requires progress on Sprint.

This task is on hold until the spring makes some progress.

**Comment by cseitz** [comment]
@NolSpencer hi im mentioning you because i want to send you a notification because fuck it why not?

**Comment by NolSpencer** [comment]
"@cseitz hi

**Comment by jkeegan1** [comment]
@cseitz @NolSpencer @cpfeifer @rsilvey1 @wesaka i made dinner last night

**Comment by cseitz** [comment]
The following was accomplished in this sprint:
1. Coloring Tasks is Pending Review before being marked Completed
2. Progress on Vision Statement
3. Progress on Business Plan

During this sprint, we did not get as much done as we would have liked.

Due to it being our first sprint, we all had unfamiliarities and uncertainties with the process itself and we were not able to get much done, but we have identified new ways to restructure and organize to be significantly better prepared for the next sprint.

The following changes have been made in an effort to resolve these problems for future sprints:
1. A shared calendar has been created with meeting times and check-in times
2. Mandatory check-in by 7 PM on Saturdays and Sundays has been established. Team Members must report what they are doing or why they are not doing anything by 7 PM on those days. This ensures we know who's doing what, that they are actually doing it, and if not; how can we adapt to work not getting done.
3. Monday meetings have been moved to before class to better prepare for the presentation of each sprint to Dr. Delozier.
4. An additional meeting on Friday from 2 to 3 PM has been scheduled for each week.
5. A shift will be made to focus on one or two team-voted feature requests per sprint, rather than being the full scope of the spirit. Many more minor features, adjustments, and bug fixes will be focused on per sprint instead.
6. In-Depth meeting notes have become official. All important meeting topics are now transcripted by the group Marketing Analyst and President.

Hopefully, these changes will make next week's sprint more programming related.
