### ISSUE TITLE
Automatically send to "Today" all the tasks in "Tomorrow" when the clock strikes 00:00

### ISSUE THREAD

**Issue by wesley-ka** [cseitz/SoftwareEngineering-Team-TGMGPA#59]
Is it just me, or this is something a person who would use the taskbook would expect?

I feel that this is the only reason that there should be "Today" and "Tomorrow" columns honestly.

**Comment by cseitz** [comment]
Possibly, but it may also get handled by default once we add task due dates.

For example, lets say that task due dates automatically move to the today column if its due within 24 hours; otherwise its in the tomorrow column.

Basically "today" and "tomorrow" would become "here's what i need to worry about now" and "here's what i need to do in the future but not right now".

Due Dates: #10

**Comment by wesley-ka** [comment]
Nice, hadn't thought in this way. For sure this will be a major selling point of our application.

**Comment by wesley-ka** [comment]
Marking this issue as closed. As when adding the due dates I kinda bundled this together.
